### ISSUE TITLE
Dismiss low contrast warning

### ISSUE THREAD

**Issue by Zenahr** [deckgo/deckdeckgo#1064]
### Affected part of DeckDeckGo

- [x] Studio (online editor)
- [ ] Remote control
- [ ] Poll
- [ ] Site
- [ ] Documentation
- [ ] Demo
- [ ] Starter kit
- [ ] Web Components
- [ ] Templates

### Feature Description

Add a `Dismiss` button to `low contrast warnings` that will make the warning disappear altogether.

### Use Case

Evidently the low contrast warning pops up in cases where it shouldn't pop up. I would like to generally have an option to opt out of the warning since it is distracting while working on slides.

### Additional Notes

This is a slide I've gotten the warning for:
![image](https://user-images.githubusercontent.com/47085752/105855579-87c7c600-5fe8-11eb-8261-6364b3f4187b.png)

upon clicking the `Got it` button the warning does not disappear.
![image](https://user-images.githubusercontent.com/47085752/105855711-a928b200-5fe8-11eb-9d95-c660cc4ca9c9.png)

**Comment by peterpeterparker** [comment]
Sure, that's totally doable!

In addition we should probably also add the option to the  "settings > customization" so that the user can trigger it back to "active".

That being said, if the contrast warning popups when it should not, we should also in parallel try to fix these cases 😅. 

<img width="1128" alt="Capture d’écran 2021-01-26 à 15 14 36" src="https://user-images.githubusercontent.com/16886711/105856528-a1b5d880-5fe9-11eb-9061-a4323090b719.png">

**Comment by peterpeterparker** [comment]
Indeed there was a bug in the contrast detection which followed a refactoring of the color picker. I solved it in PR #1094.
I keep an eye on it if it would need more fix.

Nevertheless, fix or not, this feature remains a good idea 👍

**Comment by peterpeterparker** [comment]
Solved by @christiankozalla

Will be released in v4.8.0 🥳
