### ISSUE TITLE
Active drag, resize & rotate with JQuery

### ISSUE THREAD

**Issue by MonUj** [deckgo/deckdeckgo#1176]
### Affected part of DeckDeckGo

- [x] Web Components

Drag, resize & rotate component

### Reproduction

Steps to reproduce:

1. [https://codepen.io/LeUj/pen/abBpbBz](url)
2.

### Expected Behavior

I would like to be able to activate/desactivate  drr (drag,resize,rotate) with a button.

### Actual Behavior

What I get is parameters of my div (cf codepen) changes when I click but nothing happend. I must init the div with drag activate then I can activate/desactivate. But if all parameters are initialize at false, when I click, they switch to true but can't be drag or resize 

### Environment

Using Javascript & JQuery

- Browser(s): Opera, Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by peterpeterparker** [comment]
Thanks for the issue @MonUj 

This has been track (I opened the issue last weekend) and solved (now) in https://github.com/deckgo/deckdeckgo/issues/1173

It has been published in `v2.1.0` of the web components.

I was able to make the feature happens in your pen but, it needed some changes. Notably, it needs a container around the component, otherwise the position and other metrics cannot be calculated.

Checkout following updated pen: https://codepen.io/peterpeterparker/pen/mdWwRgN

**Comment by MonUj** [comment]
Hi David,

Thanks a lot for helping me to do this task. I really appreciate you taking
time with me for information and exchange. I wish you the best for the rest.

Now I'll try to implement this on my work project ! Hope it will not be too
hard aha !

Thx again,
Best regards,
Julien

Le mar. 25 mai 2021 à 17:51, David Dal Busco ***@***.***> a
écrit :

**Comment by peterpeterparker** [comment]
My pleasure and thanks for raising the idea!

Have fun with your project
