### ISSUE TITLE
Remote control timer 

### ISSUE THREAD

**Issue by artezan** [deckgo/deckdeckgo#138]
On the remote control timer when you set a time on `ion-datetime`  on the method `initTimerLengthAndStartTimer()` of the file **app-timer.tsx** in the line 206, `hours` and  `minutes` are incorrect, instep of:

``` javascript
  const hours: number = parseInt(values[0], 0);
  const minutes: number = parseInt(values[1], 0);
```
Replace to:

```javascript
const dateSelected: Date = new Date($event.detail.value);
const hours: number = dateSelected.getHours();
const minutes: number = dateSelected.getMinutes();

```
And then you need to change:

```javascript
const length: number = (minutes * 60 * 1000) + (hours * 60 * 60 * 1000);
```
to:

```javascript
const length: number = dateSelected.getTime() - new Date().getTime();
```

I highly recommend use vanilla javascript for dates and always use milliseconds for all your operations with times

**Comment by peterpeterparker** [comment]
`ion-datetime` didn't used to return a date which was supported across browser that's why it was not safe to rely on a date.

That being said, it seems now that it's the case and furthermore, it needed also some other improvements as the Ionic component was modified, thx for pointing this out!

P.S.: following

```
const length: number = dateSelected.getTime() - new Date().getTime();
```

would not work as the component is used to select a duration (hours:minutes) and not a specific time. therefore, as I already used `date-fns` in the app, my solution is the following:

```
differenceInMilliseconds(selected, startOfDay(new Date()))
```
