### ISSUE TITLE
using deckdeckgo offline ?

### ISSUE THREAD

**Issue by xinity** [deckgo/deckdeckgo#402]
hello there,

I've stumbled upon this awesome project and I've been wondering if we are able to use it (studio included) offline?
I've tried the getting started, but it yells about a missing JSON dev configuration file.

Have I missed something in the process?

Let me know,

Keep up the awesome work folks this looks tremendously exciting

Cheers

**Comment by peterpeterparker** [comment]
Hi,

Thx for reaching out and the nice message 😃

"studio" our editor doesn't provide any offline mode yet. It's something we've got in mind for the future.

the missing configuration is known and documented in the [contributing guide](https://github.com/deckgo/deckdeckgo/blob/master/CONTRIBUTING.md). we actually don't expose the tokens and keys of our database and servers in the repo because you know, the costs are linked with our private cards but we are really happy to provide these information through PM for the contributors. note that it is also something which might change in the future, I'm thinking about exposing the development configuration but I should still think a bit about it.

I hope this answer your questions, ping me if you've got more, happy to answer or to help

Best regards
David

P.S.: I gonna close this issue as it isn't a feature request or bug. you could reach me anytime one of our others [channels](https://deckdeckgo.com/contact)
