### ISSUE TITLE
Feature to change position , size and orientation of Text Boxes

### ISSUE THREAD

**Issue by nateshmbhat** [deckgo/deckdeckgo#416]

**Comment by peterpeterparker** [comment]
if I understand correctly you would like to be able to "move the text boxes anywhere, change their size and orientation".

well, I understand that, but summarized, currently, the templates and content are given and somehow limited as the goal of the project it to provide presentations which

1. looks good on any devices respectively mobile, tablet, computer or projector 

and

2.  has for goal to ship these as progressive web app

that's why "position, size and orientation" are kind of to be "fixed" and defined by templates notably.

that being said, new templates in the future might introduce others positions, sizes and orientations you would be looking for.

for that reason I close the issue as it is a bit too general and will be naturally improved by the addition of more templates in the future.

p.s.: regarding text size, it's already possible to select between different size (huge title, paragraph etc.)
