### ISSUE TITLE
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

### ISSUE THREAD

**Issue by JonnyTech** [deckgo/deckdeckgo#516]
Going to https://deckdeckgo.com/ in Firefox 70.0.1 64 bit on Debian Buster based Linux, just getting a blank screen.

The developer console displays the following:

```
DeckDeckGo
Hey there, interested by our code? Lucky you, we are open source :)
Come say hi and contribute to our project on Github
https://github.com/deckgo/deckdeckgo
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
```

Loads correctly in Chromium. Any ideas?

**Comment by peterpeterparker** [comment]
@JonnyTech thank you for reaching out 👍 

Did you tried it maybe in an incognito Firefox browser/tab?

If I try "normal mode" Firefox it works fine for me but if I do try it in incognito mode, then I also face thee error `InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.`

If it's also your case, then I would say that's the reason and that probably this happens because IndexedDB isn't supported by Firefox in private mode (https://bugzilla.mozilla.org/show_bug.cgi?id=781982)

Does that makes sense or you do face the problem in "standard mode" too?

My screenshots:

<img width="1516" alt="Capture d’écran 2019-12-04 à 14 58 04" src="https://user-images.githubusercontent.com/16886711/70148846-3ef7d400-16a7-11ea-8fe1-e0204f969713.png">
<img width="1516" alt="Capture d’écran 2019-12-04 à 14 58 24" src="https://user-images.githubusercontent.com/16886711/70148847-3f906a80-16a7-11ea-9cfc-5ad971a3e265.png">

**Comment by JonnyTech** [comment]
Ah, yes, in Firefox it is set to never remember history which is the same as private mode. Thanks for confirming. I wonder if I can exclude that site only..

**Comment by peterpeterparker** [comment]
@JonnyTech thx you for the feedback. I hope there is such a solutio (exclude site), that would be great!

I've to say I like to use idb and specially through [idb-keyval](https://github.com/jakearchibald/idb-keyval) because it's a lightweight and fast library
