### ISSUE TITLE
studio: remote control text is not readable

### ISSUE THREAD

**Issue by donroyco** [deckgo/deckdeckgo#545]
### Affected part of DeckDeckGo
- [x] Studio
- [ ] Remote control
- [ ] Documentation
- [ ] Demo
- [ ] Starter kit
- [ ] Poll
- [ ] Web Components
- [ ] Templates

#### Reproduction

Steps to reproduce:
1. Go to editor
2. Click 'Remote' option
3. See the modal popping up
 
#### Expected Behavior

To be able to read all of the text that's displayed.

#### Actual Behavior

<img width="708" alt="Remote modal text" src="https://user-images.githubusercontent.com/1763537/70861854-1d62dc00-1f34-11ea-91a5-1f9c8abaa66b.png">

This text (Remote control your...) is very hard to read. I would suggest to make it bigger (maybe even `var(--font-size-normal)`) and then make it grey to keep the hierarchy on the page.

#### Environment

- Browser(s): Chrome, latest version
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by peterpeterparker** [comment]
sure good suggestion, thx 👍

**Comment by peterpeterparker** [comment]
I went with `--font-size-small` instead of `--font-size-very-small`. I see the info as hint, that's why I also moved it at the bottom of the modal.

Let me know what you think about it.

<img width="1293" alt="Capture d’écran 2020-01-06 à 08 13 39" src="https://user-images.githubusercontent.com/16886711/71801873-7b2ea380-305c-11ea-821e-29f5193dfb60.png">

**Comment by donroyco** [comment]
Looks way better. Thanks!

**Comment by peterpeterparker** [comment]
super @donroyco ! thx you for the issue and feedback 👍
