### ISSUE TITLE
Cannot use DeckDeckGo in Firefox Private Window

### ISSUE THREAD

**Issue by fluffynuts** [deckgo/deckdeckgo#827]
### Affected part of DeckDeckGo
- [x] All of it (:
- [ ] Studio
- [ ] Remote control
- [ ] Documentation
- [ ] Demo
- [ ] Starter kit
- [ ] Poll
- [ ] Web Components
- [ ] Templates

### Reproduction

Steps to reproduce:
1. Open Firefox Private Window
2. Attempt to launch deckdeckgo.com
3. White screen
 
 
### Expected Behavior

DeckDeckGo goodness!

### Actual Behavior

Just got a white screen )':

### Environment

- Firefox 78.0.2 (64-bit)
- Gentoo Linux

### More
I understand that DeckDeckGo is not expected to work in a private browser due to the way Firebase is used. It's unfortunate, but if that's accepted behavior, it would at least be nice to present a message to the user that there was a problem loading up DeckDeckGo, and perhaps, if they are using a private browser, they should try to use a non-private one; ideally, there's also a link to a more technical explanation so that curious cats like myself can read up and feel smart for knowing stuff!

**Comment by peterpeterparker** [comment]
Related issues I found:

https://github.com/firebase/firebase-js-sdk/issues/801

https://github.com/firebase/firebase-js-sdk/issues/2373

And this seems the open feature at Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1562669

**Comment by peterpeterparker** [comment]
Ok so actually this is not a Firebase issue but rather a Firebase Incognito mode related to IndexedDB and idb-keyl

This is the issue about it: https://github.com/jakearchibald/idb-keyval/issues/32
And the solution to make  it works in Firefox seems to be by enabling `remember history`

**Comment by peterpeterparker** [comment]
I  have to say I went with the cheapest solution aka adding a `console.error` over the authentication. In order to be able to display the app and a message that would need more time so I think it is ok in that way. I hope you share this point of view.

Thanks again for raising the issue.

<img width="1315" alt="Capture d’écran 2020-08-07 à 12 15 25" src="https://user-images.githubusercontent.com/16886711/89635819-e4eb8600-d8a7-11ea-9df7-401c683974ac.png">
