### ISSUE TITLE
Using @deckdeckgo/color with webpack does not seem to work

### ISSUE THREAD

**Issue by Artur-** [deckgo/deckdeckgo#852]
### Affected part of DeckDeckGo
- [ ] Studio
- [ ] Remote control
- [ ] Documentation
- [ ] Demo
- [ ] Starter kit
- [ ] Poll
- [X] Web Components: color
- [ ] Templates

### Reproduction

Steps to reproduce:
1. 
```
git clone https://github.com/wbkd/webpack-starter colortest
cd colortest/
npm i --save @deckdeckgo/color
```
2. Add ` <deckgo-color></deckgo-color>` to `src/index.html`
3. Follow https://docs.deckdeckgo.com/components/color/ and add `import '@deckdeckgo/color';` to `src/scripts/index.js`
4. Run `npm start` and open localhost:8080
 
### Expected Behavior

The `deckgo-color` component should be visible

### Actual Behavior

No component is visible. `customElements.get("deckgo-color")` is undefined

If you change the import to a similar one that is used for unpkg: `import "@deckdeckgo/color/dist/deckdeckgo-color/deckdeckgo-color.esm.js";` then a lot more is loaded but it ultimately fails in the browser with
```
TypeError: Cannot read property 'data-opts' of undefined
```
which seems to originate in some kind of import path detection based on a `<script>` tag that does not exist.

### Environment

- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS

**Comment by peterpeterparker** [comment]
Thank you for the well detailed issue @Artur-  👍 

The component is not loaded as the `loader` has to be use with such `webpack` project.

As in the [doc](https://docs.deckdeckgo.com/components/color/), instead of the `import '@deckdeckgo/color';`, you can do as following.

```
import { defineCustomElements as deckDeckGoElement } from '@deckdeckgo/color/dist/loader';
deckDeckGoElement();
```

I tried your given steps and it worked out (see screenshot). Therefore I close this issue but  if you have more questions, let me know!

<img width="1135" alt="Capture d’écran 2020-08-24 à 16 48 56" src="https://user-images.githubusercontent.com/16886711/91059451-04b1d680-e62a-11ea-96e0-385ed51e8a51.png">
