### ISSUE TITLE
studio: add custom colors at end of color palette

### ISSUE THREAD

**Issue by donroyco** [deckgo/deckdeckgo#919]
### Affected part of DeckDeckGo
- [x] Studio

 
### Feature Description

![Screenshot 2020-10-06 at 19 15 45](https://user-images.githubusercontent.com/1763537/95238067-46c55f00-0809-11eb-874f-f5006e188d2f.png)
_Two custom colors added at the beginning of the color palette._

Current custom colors (awesome feature introduced in #902 ) are being added at the beginning of the color palette. It then shifts the full row(s) of colors to the next line. If you add another color, the row shifts again. And so fort. I think it would be nicer to add it to the end of the color list to not have shifts in default color set; it would also be easier known what the defaults are.

For example:

**Adobe Photoshop** adds colors (swatches) to the end of the default list.

![image](https://user-images.githubusercontent.com/1763537/95237719-d9193300-0808-11eb-96f0-425da090f1c8.png)
Source: [Adobe Photoshop](https://helpx.adobe.com/sea/photoshop/using/customizing-color-pickers-swatches.html)

**Sketch** also adds colors to the end of the default list.

<img width="285" alt="Screenshot 2020-10-06 at 18 37 57" src="https://user-images.githubusercontent.com/1763537/95238015-37deac80-0809-11eb-806d-8bc412c89f6d.png">
Source: Sketch

### Benefits:
- Your muscle memory still remembers the original order
- No violation of _[spatial consistency](https://www.nngroup.com/articles/top-10-application-design-mistakes/)_ (see 2. Inconsistency)

### Discussion
It's nice to have a discussion on this.

**Comment by HugoLiconV** [comment]
If this is needed I could take a look at it

**Comment by peterpeterparker** [comment]
@HugoLiconV it is not yet ready for development. The idea is first to discuss about the possible enhancement.
If you have any inputs about it, let us know.

**Comment by peterpeterparker** [comment]
This [color picker](https://omgovich.github.io/react-colorful/) (seen on [dev](https://dev.to/omgovich/react-colorful-1-8-kb-color-picker-for-react-fast-dependency-free-customizable-and-accessible-8le)) for react is nice too.

Its design does not solve all our requirements such as keep the history of used colors and the accessibility (displaying the color value in text form) but I like the way it managed to display opacy and colors in a single block.

**Comment by peterpeterparker** [comment]
Note for my self: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color

**Comment by peterpeterparker** [comment]
I had some ideas and also will mix it with quite a refactoring. I'll develop something and comeback with a suggestion asap.

**Comment by peterpeterparker** [comment]
After analyzing the requirements of the "color picker" of our editor I came to the conclusion that the most important feature is being able to enter (keyboard input) the color values, thus because when users are, or at least I am, creating presentations, these are often related to their project or company.

This is currently not solve in an user friendly as we are relying on the browser native color picker for such purpose.

Likewise, once specific color are added, it is useful for the user to be able to reuse these quickly without the need  of using the keyboard again.

Summarized, to me the priority are:

- enter color keyboard (hex or rgb)
- color history
- color picker (mouse / touch selection of a color)
- reset, opacity etc.

That's why, I tried to implement such a feature and began a refactoring of all color picker of the editor. See screenshot.

@donroyco what do you think about it? 

The related PR is #974. I am currently refactoring the different features but already implemented it in the most common case (font / background color of deck, slide and element)

<img width="1208" alt="Capture d’écran 2020-10-25 à 20 36 39" src="https://user-images.githubusercontent.com/16886711/97117134-184cec80-1702-11eb-8f6d-51f852683296.png">

**Comment by peterpeterparker** [comment]
@donroyco each time a color is selected, it becomes the first in the history stack. not sure if it a good behavior or not, I'll be interested to hear your thought about this too.

**Comment by peterpeterparker** [comment]
We are in the release process, therefore I included/mergeed my PR. Happy to hear any feedback, positive or negative, and to perform any improvements in several other PRs.

**Comment by donroyco** [comment]
Okay: here are a few remarks:
- The first one in history is okay, as long as there are no colors in front (default color set, see point 2).
- I am wondering why you got rid of the default color set? Sometimes you just want a quick presentation without too much hassle to create your own palette. The default color palette was nice to speed things.
- A11y: the slider of opacity has no visual focus state.
- A11y: the color history items have no clear visual focus state (only slightly a shadow).

**Comment by peterpeterparker** [comment]
thx for the feedback @donroyco 👍 

- cool
- done. the  default palette is back
- I had a look but actually did not find how to outline the focus with the ion-range component 🤔
- it's because I use ion-tab-button which can displays their focus with a  background color, what does not work best for the use. we should probably use and style button instead, if you are up for a PR, go for it!
